### ISSUE TITLE
TagBot broken?

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Scratch.jl#47]
I released Scratch.jl 1.2.1 earlier today, but somehow TagBot did not end up creating a tag for it. Anybody got an idea what might be wrong? I already updated the TagBot.yml to the latest a while ago, so that's not it. Rather, TagBot did not comment on https://github.com/JuliaPackaging/Scratch.jl/issues/31 -- why not?

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pull/94603

**Comment by fingolfin** [comment]
Ouch! Sorry for the noise then! I somehow could have sworn I saw a mail that it was merged, but clearly I was dead wrong. OK, that's easy to take of then, I am on it.

**Comment by giordano** [comment]
TagBot ran after the PR above was actually merged, and now we finally have [deployed docs](https://juliapackaging.github.io/Scratch.jl/stable/) as well.
